// GENERATED by tools/gen_top_panel.py -- DO NOT EDIT BY HAND
//
// Top-panel layout shared by the laser template and the printed lid.
// enclosure/top_panel_cutout.svg is generated from these same numbers,
// so a change here reaches both routes at once. Edit the generator, not
// this file.
//
// Coordinates are OpenSCAD-native: origin front-left, Y up, mm.

PANEL_W  = 210;
PANEL_H  = 140;   // depth in plan view
CORNER_R = 8;
PANEL_T  = 2.8;   // top face thickness

// dia 10 x 3 mm coin motors, 0.4 mm total fit clearance
MOTOR_DIA_NOM  = 10;
MOTOR_T        = 3;
MOTOR_HOLE_DIA = 10.4;
// dots 1-6 in order
MOTOR_POS = [ [37, 114], [37, 84], [37, 54], [67, 114], [67, 84], [67, 54] ];

// 12 x 12 x 6 mm 4-pin tactile switches, square cutout
BTN_BODY     = 12;
BTN_HOLE     = 12.4;
BTN_HOLE_R   = 0.5;
// dots 1-6 then submit
BTN_POS = [ [143, 114], [143, 84], [143, 54], [173, 114], [173, 84], [173, 54], [158, 24] ];

// perforated area dia 34.5 mm, under a dia 40 mm speaker
SPEAKER_DIA    = 40;
GRILL_HOLE_DIA = 2.5;
GRILL_POS = [ [105, 28], [105, 33.5], [109.763, 30.75], [109.763, 25.25], [105, 22.5], [100.237, 25.25], [100.237, 30.75], [105, 39], [110.5, 37.5263], [114.526, 33.5], [116, 28], [114.526, 22.5], [110.5, 18.4737], [105, 17], [99.5, 18.4737], [95.4737, 22.5], [94, 28], [95.4737, 33.5], [99.5, 37.5263], [105, 44], [110.472, 43.0351], [115.285, 40.2567], [118.856, 36], [120.757, 30.7784], [120.757, 25.2216], [118.856, 20], [115.285, 15.7433], [110.472, 12.9649], [105, 12], [99.5277, 12.9649], [94.7154, 15.7433], [91.1436, 20], [89.2431, 25.2216], [89.2431, 30.7784], [91.1436, 36], [94.7154, 40.2567], [99.5277, 43.0351] ];

// M3 clearance
SCREW_DIA = 3.2;
SCREW_POS = [ [8, 132], [202, 132], [8, 8], [202, 8] ];
