// GENERATED by tools/gen_braille_header.py from data/braille_map.json -- DO NOT EDIT
// standard: Bangladesh_National_Braille_Code   verified: True
#ifndef BRAILLE_MAP_H
#define BRAILLE_MAP_H

#include <stdint.h>

#define BRAILLE_LETTER_COUNT 50
#define BRAILLE_MAP_VERIFIED 1   // 1 only when ALL letters are verified
#define BRAILLE_VERIFIED_COUNT 50
#define BRAILLE_VOWEL_COUNT 11

// Per-letter provenance. Images arrive in batches, so verification is tracked
// per character rather than as one flag: 1 = read from a supplied image,
// 0 = still a Bharati placeholder guess. The sketch stamps this into each
// logged row, so rows for verified characters stay usable even while the rest
// of the alphabet is unconfirmed.
static const uint8_t BRAILLE_VERIFIED[BRAILLE_LETTER_COUNT] = {
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1
};

// Bit i set => dot i+1 is raised.  bit0=dot1 bit1=dot2 bit2=dot3
//                                  bit3=dot4 bit4=dot5 bit5=dot6
// Index is the letter id, which matches feature 0 (char_id) exactly.
// For two-cell characters (BRAILLE_PREFIX[id] != 0), this is the SECOND cell
// (the answer cell the learner presses). The first cell is in BRAILLE_PREFIX.
static const uint8_t BRAILLE_PATTERN[BRAILLE_LETTER_COUNT] = {
  0x01,  //  0  অ  a              dots 1
  0x1C,  //  1  আ  aa             dots 3-4-5
  0x0A,  //  2  ই  i              dots 2-4
  0x14,  //  3  ঈ  ii             dots 3-5
  0x25,  //  4  উ  u              dots 1-3-6
  0x33,  //  5  ঊ  uu             dots 1-2-5-6
  0x17,  //  6  ঋ  ri             dots 1-2-3-5  2-cell: prefix 5
  0x11,  //  7  এ  e              dots 1-5
  0x0C,  //  8  ঐ  oi             dots 3-4
  0x15,  //  9  ও  o              dots 1-3-5
  0x2A,  // 10  ঔ  ou             dots 2-4-6
  0x05,  // 11  ক  ka             dots 1-3
  0x2D,  // 12  খ  kha            dots 1-3-4-6
  0x1B,  // 13  গ  ga             dots 1-2-4-5
  0x23,  // 14  ঘ  gha            dots 1-2-6
  0x2C,  // 15  ঙ  uma            dots 3-4-6
  0x09,  // 16  চ  cha            dots 1-4
  0x21,  // 17  ছ  chha           dots 1-6
  0x1A,  // 18  জ  ja             dots 2-4-5
  0x35,  // 19  ঝ  jha            dots 1-3-5-6
  0x12,  // 20  ঞ  nia            dots 2-5
  0x3E,  // 21  ট  tta            dots 2-3-4-5-6
  0x3A,  // 22  ঠ  ttha           dots 2-4-5-6
  0x2B,  // 23  ড  dda            dots 1-2-4-6
  0x3F,  // 24  ঢ  ddha           dots 1-2-3-4-5-6
  0x3C,  // 25  ণ  nna            dots 3-4-5-6
  0x1E,  // 26  ত  ta             dots 2-3-4-5
  0x39,  // 27  থ  tha            dots 1-4-5-6
  0x19,  // 28  দ  da             dots 1-4-5
  0x2E,  // 29  ধ  dha            dots 2-3-4-6
  0x1D,  // 30  ন  na             dots 1-3-4-5
  0x0F,  // 31  প  pa             dots 1-2-3-4
  0x16,  // 32  ফ  pha            dots 2-3-5
  0x03,  // 33  ব  ba             dots 1-2
  0x27,  // 34  ভ  bha            dots 1-2-3-6
  0x0D,  // 35  ম  ma             dots 1-3-4
  0x3D,  // 36  য  ya             dots 1-3-4-5-6
  0x17,  // 37  র  ra             dots 1-2-3-5
  0x07,  // 38  ল  la             dots 1-2-3
  0x29,  // 39  শ  sha            dots 1-4-6
  0x2F,  // 40  ষ  ssa            dots 1-2-3-4-6
  0x0E,  // 41  স  sa             dots 2-3-4
  0x13,  // 42  হ  ha             dots 1-2-5
  0x3B,  // 43  ড়  rra            dots 1-2-4-5-6
  0x37,  // 44  ঢ়  rha            dots 1-2-3-5-6
  0x22,  // 45  য়  yya            dots 2-6
  0x1E,  // 46  ৎ  khanda_ta      dots 2-3-4-5  2-cell: prefix 5
  0x30,  // 47  ং  anushar        dots 5-6
  0x20,  // 48  ঃ  bisharga       dots 6
  0x04,  // 49  ঁ  chandrabindu   dots 3
};

// Prefix (first cell) for two-cell characters. 0 means single-cell.
// Before collecting the learner's answer, vibrate this cell briefly, then pause.
static const uint8_t BRAILLE_PREFIX[BRAILLE_LETTER_COUNT] = {
  0x00,  //  0  অ
  0x00,  //  1  আ
  0x00,  //  2  ই
  0x00,  //  3  ঈ
  0x00,  //  4  উ
  0x00,  //  5  ঊ
  0x10,  //  6  ঋ
  0x00,  //  7  এ
  0x00,  //  8  ঐ
  0x00,  //  9  ও
  0x00,  // 10  ঔ
  0x00,  // 11  ক
  0x00,  // 12  খ
  0x00,  // 13  গ
  0x00,  // 14  ঘ
  0x00,  // 15  ঙ
  0x00,  // 16  চ
  0x00,  // 17  ছ
  0x00,  // 18  জ
  0x00,  // 19  ঝ
  0x00,  // 20  ঞ
  0x00,  // 21  ট
  0x00,  // 22  ঠ
  0x00,  // 23  ড
  0x00,  // 24  ঢ
  0x00,  // 25  ণ
  0x00,  // 26  ত
  0x00,  // 27  থ
  0x00,  // 28  দ
  0x00,  // 29  ধ
  0x00,  // 30  ন
  0x00,  // 31  প
  0x00,  // 32  ফ
  0x00,  // 33  ব
  0x00,  // 34  ভ
  0x00,  // 35  ম
  0x00,  // 36  য
  0x00,  // 37  র
  0x00,  // 38  ল
  0x00,  // 39  শ
  0x00,  // 40  ষ
  0x00,  // 41  স
  0x00,  // 42  হ
  0x00,  // 43  ড়
  0x00,  // 44  ঢ়
  0x00,  // 45  য়
  0x10,  // 46  ৎ
  0x00,  // 47  ং
  0x00,  // 48  ঃ
  0x00,  // 49  ঁ
};

// Kept in PROGMEM-free plain flash; only used for SD-card log lines.
static const char *const BRAILLE_NAME[BRAILLE_LETTER_COUNT] = {
  "a",
  "aa",
  "i",
  "ii",
  "u",
  "uu",
  "ri",
  "e",
  "oi",
  "o",
  "ou",
  "ka",
  "kha",
  "ga",
  "gha",
  "uma",
  "cha",
  "chha",
  "ja",
  "jha",
  "nia",
  "tta",
  "ttha",
  "dda",
  "ddha",
  "nna",
  "ta",
  "tha",
  "da",
  "dha",
  "na",
  "pa",
  "pha",
  "ba",
  "bha",
  "ma",
  "ya",
  "ra",
  "la",
  "sha",
  "ssa",
  "sa",
  "ha",
  "rra",
  "rha",
  "yya",
  "khanda_ta",
  "anushar",
  "bisharga",
  "chandrabindu"
};

static const char *const BRAILLE_ROMAN[BRAILLE_LETTER_COUNT] = {
  "o",
  "a",
  "i",
  "ee",
  "u",
  "oo",
  "ri",
  "e",
  "oi",
  "o",
  "ou",
  "ka",
  "kha",
  "ga",
  "gha",
  "nga",
  "cha",
  "chha",
  "ja",
  "jha",
  "nya",
  "ta",
  "tha",
  "da",
  "dha",
  "na",
  "ta",
  "tha",
  "da",
  "dha",
  "na",
  "pa",
  "pha",
  "ba",
  "bha",
  "ma",
  "ja",
  "ra",
  "la",
  "sha",
  "sha",
  "sa",
  "ha",
  "ra",
  "rha",
  "ya",
  "t",
  "ng",
  "h",
  "n"
};

// DFPlayer track number for letter id (files are /mp3/0001.mp3 .. /mp3/0050.mp3)
static inline uint16_t braille_track(uint8_t letter_id) {
  return (uint16_t)letter_id + 1;
}

static inline uint8_t braille_dot_count(uint8_t mask) {
  uint8_t c = 0;
  for (uint8_t i = 0; i < 6; i++) if (mask & (1 << i)) c++;
  return c;
}

#endif  // BRAILLE_MAP_H
